<?php

namespace AppBundle\Repository;

/**
 * CamionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CamionRepository extends \Doctrine\ORM\EntityRepository
{
}
