<?php

namespace AppBundle\Repository;

/**
 * MarquesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarquesRepository extends \Doctrine\ORM\EntityRepository
{
}
